name: Build and Push Image to ECR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 283890144470.dkr.ecr.eu-central-1.amazonaws.com/buck-cat

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::283890144470:role/GitHub-Actions-ECR
          aws-region: ${{ env.AWS_REGION }}
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build, tag, and push the Front-End Docker Image to Amazon ECR
        env:
          REGISTRY: ${{ steps.logic-ecr-outputs.registry }}
          REPOSITORY: ./FrontEnd
        run: |
          docker build -t $REGISTRY/frontend:latest .
          docker push $REGISTRY/frontend:latest


      
      # -
      #   name: Build, tag, and push the front-end image to Amazon ECR
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./FrontEnd/
      #     file: ./FrontEnd/Dockerfile
      #     push: true
      #     tags: ${{ env.ECR_REGISTRY }}/frontend:latest
      # -
      #   name: Build, tag, and push the back-end image to Amazon ECR
      #   uses: docker/build-push-action@v2
      #   with:
      #     context: ./BackEnd/
      #     file: ./BackEnd/Dockerfile
      #     push: true
      #     tags: ${{ env.ECR_REGISTRY }}/backend:latest

      