name: Build and Push Image to ECR

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

env:
  AWS_REGION: eu-central-1
  ECR_REGISTRY: 283890144470.dkr.ecr.eu-central-1.amazonaws.com/buck-cat

jobs:
  Build:
    id: Build and Push to ECR
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          #aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          #aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: arn:aws:iam::283890144470:role/GitHub-Actions-ECR
          aws-region: ${{ env.AWS_REGION }}
      -
        name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      -
        name: Build, tag, and push the Front-End Docker Image to Amazon ECR
        id: build-image
        env:
          IMAGE: ./FrontEnd
          REGISTRY: ${{ steps.logic-ecr-outputs.registry }}
          REPOSITORY: ${{ env.ECR_REGISTRY }}
          IMAGE_TAG: frontend-latest
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}:$IMAGE_TAG $IMAGE
          docker push ${{ env.ECR_REGISTRY }}:$IMAGE_TAG
      -
        name: Build, tag, and push the Back-End Docker Image to Amazon ECR
        id: build-image
        env:
          IMAGE: ./BackEnd
          REGISTRY: ${{ steps.logic-ecr-outputs.registry }}
          REPOSITORY: ${{ env.ECR_REGISTRY }}
          IMAGE_TAG: backend-latest
        run: |
          docker build -t ${{ env.ECR_REGISTRY }}:$IMAGE_TAG $IMAGE
          docker push ${{ env.ECR_REGISTRY }}:$IMAGE_TAG    